services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      command: >
        bash -c "
        cd ssproject/ &&
        python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        python manage.py createsuperuser --username admin --email admin@example.com --noinput &&
        python manage.py runserver --bind 0.0.0.0:8000
        "
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  postgres_data:
  usr-data:
