# Generated by Django 4.2 on 2024-08-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=20,
                        verbose_name="Пароль для доступа к протоколу IMAP",
                    ),
                ),
            ],
        ),
    ]
