# Generated by Django 4.2 on 2024-08-07 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("message_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="password",
            field=models.CharField(
                max_length=20, verbose_name="Пароль для доступа по протоколу IMAP"
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=80, verbose_name="Тема сообщения"),
                ),
                ("date_send", models.DateTimeField(verbose_name="Дата отправки")),
                ("date_receiving", models.DateTimeField(verbose_name="Дата получения")),
                ("text_message", models.TextField(verbose_name="текст сообщения")),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message_service.mail",
                        verbose_name="Эл.почта",
                    ),
                ),
            ],
        ),
    ]
