# Generated by Django 4.2 on 2024-08-07 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("message_service", "0002_alter_mail_password_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mail",
            options={
                "verbose_name": "Электронная почта",
                "verbose_name_plural": "Электронные почты",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
    ]
