# Generated by Django 4.2 on 2024-08-07 19:49

from django.db import migrations, models
import django.db.models.deletion
import message_service.models


class Migration(migrations.Migration):
    dependencies = [
        ("message_service", "0003_alter_mail_options_alter_message_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        unique=True,
                        upload_to=message_service.models.upload_to_file,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message_service.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
