# Generated by Django 4.2 on 2024-08-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("message_service", "0004_filemessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImapServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, verbose_name="Наименование imap сервера"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="filemessage",
            options={"verbose_name": "Файл", "verbose_name_plural": "Файлы"},
        ),
        migrations.AddField(
            model_name="mail",
            name="sever",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="message_service.imapserver",
            ),
        ),
    ]
