# Generated by Django 4.2 on 2024-08-11 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("message_service", "0005_imapserver_alter_filemessage_options_mail_sever"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mail",
            old_name="sever",
            new_name="server",
        ),
    ]
