# Generated by Django 4.2 on 2024-08-11 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("message_service", "0007_alter_imapserver_options_message_id_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="id_message",
        ),
    ]
