# Generated by Django 4.2 on 2024-08-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message_service", "0008_remove_message_id_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(verbose_name="Тема сообщения"),
        ),
        migrations.AlterUniqueTogether(
            name="message",
            unique_together={
                ("title", "date_send", "date_receiving", "text_message", "mail")
            },
        ),
    ]
