# Generated by Django 4.2 on 2024-08-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message_service", "0009_alter_message_title_alter_message_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.TextField(verbose_name="Тема сообщения"),
        ),
    ]
